### ISSUE TITLE
Latest librsync version not working

### ISSUE THREAD

**Issue by gmenegatti** [Hitachi-Data-Systems/librsyncWrapper#1]
Apparently librsync made some "recent" changes and the wrapper is no longer working.

**Comment by gmenegatti** [comment]
Hi @bethtirado , 

Please, is there any chance you can help us figuring out what changed from the librsync version that was used when this wrapper was released to the current/latest librsync version?

Thanks in advance.

**Comment by bethtirado** [comment]
Hi @gmenegatti,

I haven't worked on this or used the librsyncWrapper since I wrote it 3 years ago.  I am no longer with Hitachi Data Systems, which is where I wrote it.

I can try and take a look over the weekend if you are still having problems, but until then, I just don't have time.

-beth

**Comment by gmenegatti** [comment]
Hi @bethtirado ,

Thanks for your reply.

So sorry, I didn't know you left Hitachi Data Systems.

It would be really amazing if you could take a look and help us on that, because we tried everything already, although our knowledge in C is very limited.

Right now we have a version that is working using the librsync version 0.9.7, but that's very old and many things were improved and correct on the most recent versions.

Thank so much for your willingness to help.

Regards,
Gabriel.

**Comment by bethtirado** [comment]
I got it to work with the latest version of librsync.   librsync changed the signature of rs_sig_begin(), so I had to make a corresponding one-line change to LibrsyncWrapper.c

Change line 64 from c/LibrsyncWrapper.c from:
```
rs_job_t *job = rs_sig_begin((size_t) blockSize, RS_MD4_LENGTH);
```
to
```
 rs_job_t *job = rs_sig_begin((size_t) blockSize, 0, RS_BLAKE2_SIG_MAGIC);
```

Notice that above, not only did the last argument change, but that a new argument (0) was added:
**RS_MD4_LENGTH**  becomes **0, RS_BLAKE2_SIG_MAGIC**.

That's it; otherwise, everything should work fine.  (Note that there is no longer a librsync-config.h, so you don't need to copy that from librsync to the c directory per the README)

Hope that helps.

-beth

**Comment by bethtirado** [comment]
I have pushed an OSX branch that contains the fix, and includes updated README and make file for OSX

**Comment by gmenegatti** [comment]
Hi @bethtirado , 

I'm honestly impressed by your attitude of using your weekend's time to help others (us in this case).

Congratulations and thanks so much for that. 

Please, just let me know if there is any way that we can contribute to you.

Regards,
Gabriel.

**Comment by bethtirado** [comment]
My pleasure.  Happy coding.  :-)
